# Generated by Django 5.2.5 on 2026-07-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_totp_enabled_user_totp_secret_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='allow_self_registration',
            field=models.BooleanField(default=True),
        ),
    ]
