# Generated by Django 5.2.5 on 2026-07-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_allow_self_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp_drift_steps',
            field=models.SmallIntegerField(default=0),
        ),
    ]
