# Generated by Django 5.2.5 on 2026-07-26 07:50

import django.db.models.deletion
import storage.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('node_type', models.CharField(choices=[('file', 'File'), ('folder', 'Folder')], max_length=10)),
                ('content', models.FileField(blank=True, upload_to=storage.models.object_upload_path)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('checksum_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('starred', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='accounts.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_nodes', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='storage.filenode')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('target_name', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='accounts.organization')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='storage.filenode')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ShareGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('permission', models.CharField(choices=[('view', 'Can view'), ('edit', 'Can edit'), ('share', 'Can share')], default='view', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants_created', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_grants', to='storage.filenode')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_with_me', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('permission', models.CharField(choices=[('view', 'Can view'), ('edit', 'Can edit'), ('share', 'Can share')], default='view', max_length=10)),
                ('password_hash', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='storage.filenode')),
            ],
        ),
        migrations.AddIndex(
            model_name='filenode',
            index=models.Index(fields=['organization', 'parent', 'deleted_at'], name='storage_fil_organiz_91e850_idx'),
        ),
        migrations.AddIndex(
            model_name='filenode',
            index=models.Index(fields=['organization', 'owner', 'deleted_at'], name='storage_fil_organiz_c93749_idx'),
        ),
        migrations.AddConstraint(
            model_name='filenode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('node_type', 'folder'), ('size_bytes', 0)), ('node_type', 'file'), _connector='OR'), name='folder_has_zero_size'),
        ),
        migrations.AddConstraint(
            model_name='sharegrant',
            constraint=models.UniqueConstraint(fields=('node', 'recipient_email'), name='unique_node_share_recipient'),
        ),
    ]
