# Generated by Django 5.2.5 on 2026-07-26 07:55

import storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filenode',
            name='content',
            field=models.FileField(blank=True, max_length=500, upload_to=storage.models.object_upload_path),
        ),
    ]
