# Generated by Django 5.2.5 on 2026-07-26 09:38

from django.db import migrations, models


def accept_existing_grants(apps, schema_editor):
    ShareGrant = apps.get_model("storage", "ShareGrant")
    ShareGrant.objects.all().update(status="accepted")


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_filenode_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharegrant',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharegrant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('ignored', 'Ignored'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=10),
        ),
        migrations.RunPython(accept_existing_grants, migrations.RunPython.noop),
    ]
